### ISSUE TITLE
Bad links from Play 2

### ISSUE THREAD

**Issue by mgifford** [GSA/Section508.gov#274]
Bad links from Play 2 - https://www.section508.gov/tools/playbooks/technology-accessibility-playbook-intro/play02/

- [IT Dashboard.gov for E-gov act accessibility related comments](https://itdashboard.gov/)
- [Agile Governance reality or dream in the US and UK Governments?](https://www.youtube.com/watch?list=PLQzq_ylfBVzKM1ZC_900nvea6uxkeAOVS&v=Wp92Vq3yTrU) (includes OMB participation link to GAO Schedule Assessment Guide)

The IT Dashboard is just the main page, not for the E-Gov Act
Youtube video is now Private

**Comment by michaelhortongsa** [comment]
Thank you for opening this issue. We have made changes to the "Play 2" page by (a) updating the hypertext (link description) to more clearly indicate that we are linking to the IT Dashboard which is a source for agency submitted E-Gov Act related summaries, and (b) removing the YouTube link for the now private video.
