### ISSUE TITLE
Broken link to PDF

### ISSUE THREAD

**Issue by mgifford** [GSA/Section508.gov#277]
This page https://www.cio.gov/about/members-and-leadership/accessibility-cop/

Last link on this line:
Review the [Executive Guide to IT Accessibility](https://section508.gov/tools/playbooks/exec-guide-accessibility) to learn more. (The Executive Guide is also [available as a PDF](https://section508.gov/sites/default/files/Executive%20Guide%20to%20Federal%20IT%20Accessibility.pdf#overlay-context=tools/playbooks).)

Links to a PDF that might have been on the Section 508 site but is broken.
https://www.section508.gov/sites/default/files/Executive%20Guide%20to%20Federal%20IT%20Accessibility.pdf#overlay-context=tools/playbooks

It can still be found here https://web.archive.org/web/20190605140544/https://www.section508.gov/sites/default/files/Executive%20Guide%20to%20Federal%20IT%20Accessibility.pdf

**Comment by michaelhortongsa** [comment]
Thank you for submitting the issue.  I have opened an issues on the CIO.gov repository requesting that they update the link to the correct URI: https://assets.section508.gov/files/Executive%20Guide%20to%20Federal%20IT%20Accessibility.pdf#overlay-context=tools/playbooks.
