### ISSUE TITLE
Font Typography article updates

### ISSUE THREAD

**Issue by bruce-usab** [GSA/Section508.gov#694]
- [ ] USBA logo is not loading on [Understanding Accessible Fonts](https://www.section508.gov/develop/fonts-typography/)
- [ ] On the 508 listserv 2024-01-24 F.S. of USDA shared some advise which might warrant incorporation.  Bruce will review and propose a PR for [the markdown page](https://github.com/GSA/Section508.gov/blob/main/_pages/develop/2023-09-23-develop-font-typography.md).

**Comment by michaelhortongsa** [comment]
Bug squished

**Comment by michaelhortongsa** [comment]
Closed
