### ISSUE TITLE
M-Index Change YoY Maturity from 2.17 down to 2.37

### ISSUE THREAD

**Issue by mgifford** [GSA/Section508.gov#953]
This is an increase, not a decrease:

Governmentwide Maturity: Average maturity increased from 2.17 to 2.37, leading to a 9% YOY increase.

https://www.section508.gov/manage/section-508-assessment/2024/findings/summary/

Did I miss something?

**Comment by drewnielson** [comment]
Thanks for the catch, Mike! Just errantly re-used the figure from the c-index figure above in our rush. We'll update shortly.
